on: push

# 添加写入权限
permissions:
  contents: write

jobs: 
  docker-push:
    name: push docker image to docker hub
    runs-on: ubuntu-latest

    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: 登录DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: 构建并推送到 DockerHub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: lexur/action-egg:latest

  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest

    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: 安装依赖 和 项目打包
        run: |
          npm install
          npm run build
          ls

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist

